# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12cb2dee42dded483044dcc8f886980b7edf8d212286d1275e34404f2c17a1c18883f7d7842bc45b7557db7194a8740103e5e880352eeb124162cf79c75f6d45

test:
  secret_key_base: 88f7077d6ddb369c62a690754e02c8122c06d5d57e0eb3d93649a93ee521de3372de91ffaec4aa1b4187b8bf69841b626036d840c28d9607eab64987d5af2777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
